//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrEngineLoader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrEngineLoader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured on COM type &apos;{0}&apos; when calling &apos;{1}&apos;..
        /// </summary>
        internal static string EXC_COM {
            get {
                return ResourceManager.GetString("EXC_COM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create &apos;{0}&apos; instance. Please make sure that &apos;{1}&apos; is registed. Use command: regsvr32 /n /i:&quot;&lt;path to FREngine.tlb folder&gt;&quot; &quot;&lt;path to {1} file&gt;&quot; to register..
        /// </summary>
        internal static string EXC_COM_SERVER_REG {
            get {
                return ResourceManager.GetString("EXC_COM_SERVER_REG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load &apos;{0}&apos; library via Kernel32.dll LoadLibraryEx() function..
        /// </summary>
        internal static string EXC_FRE_DLL_CANNOT_LOAD {
            get {
                return ResourceManager.GetString("EXC_FRE_DLL_CANNOT_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to &apos;{0}&apos; is null, empty, or consists only of white-space characters. You should specify the path when loading method &apos;{1}&apos; is set..
        /// </summary>
        internal static string EXC_FRE_DLL_EMPTY_PATH {
            get {
                return ResourceManager.GetString("EXC_FRE_DLL_EMPTY_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; doesn&apos;t exist. You should specify an existing path to &apos;{1}&apos; when loading method &apos;{2}&apos; is set..
        /// </summary>
        internal static string EXC_FRE_DLL_FILE_NOT_EXIST {
            get {
                return ResourceManager.GetString("EXC_FRE_DLL_FILE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREngine version &apos;{0}&apos; isn&apos;t supported. The supported version is &apos;{1}&apos;..
        /// </summary>
        internal static string EXC_FRE_DLL_FILE_VERSION {
            get {
                return ResourceManager.GetString("EXC_FRE_DLL_FILE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find &apos;{0}&apos; function in &apos;{1}&apos; using Kernel32.dll GetProcAddress() function..
        /// </summary>
        internal static string EXC_FRE_DLL_FUNC_SEARCH {
            get {
                return ResourceManager.GetString("EXC_FRE_DLL_FUNC_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that &apos;{0}&apos; is registed. Use command: regsvr32 /n /i:&quot;&lt;path to FREngine.tlb folder&gt;&quot; &quot;&lt;path to {0} file&gt;&quot; to register..
        /// </summary>
        internal static string EXC_FRE_DLL_NOT_REG {
            get {
                return ResourceManager.GetString("EXC_FRE_DLL_NOT_REG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to &apos;{0}&apos; expected but not to &apos;{1}&apos;. You should specify the path when loading method &apos;{2}&apos; is set..
        /// </summary>
        internal static string EXC_FRE_DLL_WRONG_PATH {
            get {
                return ResourceManager.GetString("EXC_FRE_DLL_WRONG_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot call &apos;{0}&apos; on &apos;{1}&apos; type. Probably the type &apos;{1}&apos; isn&apos;t a collection..
        /// </summary>
        internal static string EXC_GET_ENUMERATOR {
            get {
                return ResourceManager.GetString("EXC_GET_ENUMERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREngine loading method &apos;{0}&apos; isn&apos;t supported..
        /// </summary>
        internal static string EXC_LOADING_METHOD {
            get {
                return ResourceManager.GetString("EXC_LOADING_METHOD", resourceCulture);
            }
        }
    }
}
